### ISSUE TITLE
error when linking to CXX executable

### ISSUE THREAD

**Issue by VirgilioVasconc** [ideasman42/opentoonz#12]
It has happened since a few days ago, not sure about the exact day, but when I try to compile the sources on Ubuntu Linux 16.04 I get to 100% after "make" and get the following error:

```
[100%] Linking CXX executable .
/usr/bin/ld: cannot open output file .: Is a directory
collect2: error: ld returned 1 exit status
tcomposer/CMakeFiles/tcomposer.dir/build.make:120: recipe for target 'tcomposer' failed
make[2]: *** [tcomposer] Error 1
CMakeFiles/Makefile2:1136: recipe for target 'tcomposer/CMakeFiles/tcomposer.dir/all' failed
make[1]: *** [tcomposer/CMakeFiles/tcomposer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I have tried cleaning all directories to see if it was a remainder of a previous compilation, but it didn't work.

**Comment by ideasman42** [comment]
Ideally this would be fixed by changing output of binaries, for now renamed to `tcomposer.bin`
