### ISSUE TITLE
crash OpenGL assert on my PC (OpenGL関係のassertでクラッシュします)

### ISSUE THREAD

**Issue by Teiji-Matsusaka** [ideasman42/opentoonz#14]
My system does not support the GL_EXT_convolution and GL_EXT_histogram.
However glDisable execution result glGetError will return an error code 1280.
But we were to add the code to check the OpenGL extention, How do I reflect doing?
Since English is not good I use google translation. 

私のシステムはGL_EXT_convolutionとGL_EXT_histogramをサポートしていません。
しかしglDisableを実行した結果glGetErrorがエラーコード1280を返します
OpenGL extentionを確認するコードを追加したのですが、反映するにはどうしたら良いでしょうか？
英語が苦手なのでgoogle翻訳を使っています

**Comment by mmuman** [comment]
1280 = 0x500 = GL_INVALID_ENUM.
It's odd that it'd return an error just for that...
It seems that glGetError() actually queues errors, so it might be useful to pop them after the calls to glDisable(), as proposed here: https://www.opengl.org/wiki/OpenGL_Error#Testing_for_errors

Can you try with this patch?
```
diff --git a/toonz/sources/toonzlib/imagepainter.cpp b/toonz/sources/toonzlib/imagepainter.cpp
index 8b3d6a3..f4fbf9d 100644
--- a/toonz/sources/toonzlib/imagepainter.cpp
+++ b/toonz/sources/toonzlib/imagepainter.cpp
@@ -223,6 +223,10 @@ void Painter::flushRasterImages(const TRect &loadbox, double compareX, double co
 	glDisable(GL_TEXTURE_3D_EXT);
 #endif
 
+	//pop GL errors due to unimplemented extensions
+	GLenum err = GL_NO_ERROR;
+	while((err = glGetError()) != GL_NO_ERROR);
+
 	UCHAR m = m_vSettings.m_colorMask;
 	bool showBg = (m == 0 ||
 				   (m & TRop::MChan && !m_vSettings.m_greytones &&
diff --git a/toonz/sources/toonzlib/stagevisitor.cpp b/toonz/sources/toonzlib/stagevisitor.cpp
index c9dc3ed..a6b98e0 100644
--- a/toonz/sources/toonzlib/stagevisitor.cpp
+++ b/toonz/sources/toonzlib/stagevisitor.cpp
@@ -626,6 +626,10 @@ void RasterPainter::flushRasterImages()
 	glDisable(GL_TEXTURE_3D_EXT);
 #endif
 
+	//pop GL errors due to unimplemented extensions
+	GLenum err = GL_NO_ERROR;
+	while((err = glGetError()) != GL_NO_ERROR);
+
 	glPushMatrix();
 	glLoadIdentity();
 ```

**Comment by Teiji-Matsusaka** [comment]
Thank you mmuman.
I think that it is better to check the OpenGL extention.
Please consider.

tglcheckext.h ---------------------------------------
#pragma once

#ifndef TGLCHECKEXT_H
#define TGLCHECKEXT_H

#include <string>

class tglcheckext {
public:
        tglcheckext();
        bool check( std::string ext );
};

#endif

tglcheckext.cpp -----------------------------------------
#include <GL/glew.h>
#include <string.h>

#include "tglcheckext.h"

tglcheckext::tglcheckext() {
}

bool tglcheckext::check( std::string ext ) {
        const GLubyte *glver = glGetString( GL_VERSION );
        if( glver ) {
                const GLubyte *extlist = glGetString( GL_EXTENSIONS );
                if( strstr((char *)extlist, ext.c_str()) ) {
                        return true;
                }
        } else {
                GLint n;
                glGetIntegerv( GL_NUM_EXTENSIONS, &n );
                for( GLint i=0; i<n; i++) {
                        const GLubyte *exti = glGetStringi( GL_EXTENSIONS, i );
                        if( strcmp((char *)exti, ext.c_str()) ) {
                                return true;
                        }
                }
        }
        return false;
}

@@ -208,19 +209,27 @@ void Painter::flushRasterImages(const TRect &loadbox, double compareX, double co
 	glDisable(GL_LOGIC_OP);
 	glDisable(GL_STENCIL_TEST);
 
+	tglcheckext glext;
+
 #ifdef GL_EXT_convolution
-	glDisable(GL_CONVOLUTION_1D_EXT);
-	glDisable(GL_CONVOLUTION_2D_EXT);
-	glDisable(GL_SEPARABLE_2D_EXT);
+	if( glext.check("GL_EXT_convolution") ) {
+		glDisable(GL_CONVOLUTION_1D_EXT);
+		glDisable(GL_CONVOLUTION_2D_EXT);
+		glDisable(GL_SEPARABLE_2D_EXT);
+	}
 #endif
 
 #ifdef GL_EXT_histogram
-	glDisable(GL_HISTOGRAM_EXT);
-	glDisable(GL_MINMAX_EXT);
+	if( glext.check("GL_EXT_histogram") ) {
+		glDisable(GL_HISTOGRAM_EXT);
+		glDisable(GL_MINMAX_EXT);
+	}
 #endif
 
 #ifdef GL_EXT_texture3D
-	glDisable(GL_TEXTURE_3D_EXT);
+	if( glext.check("GL_EXT_texture3D") ) {
+		glDisable(GL_TEXTURE_3D_EXT);
+	}
 #endif
 
 	UCHAR m = m_vSettings.m_colorMask;

@@ -611,19 +612,27 @@ void RasterPainter::flushRasterImages()
 	glDisable(GL_DITHER);
 	glDisable(GL_LOGIC_OP);
 
+	tglcheckext glext;
+
 #ifdef GL_EXT_convolution
-	glDisable(GL_CONVOLUTION_1D_EXT);
-	glDisable(GL_CONVOLUTION_2D_EXT);
-	glDisable(GL_SEPARABLE_2D_EXT);
+	if( glext.check("GL_EXT_convolution") ) {
+		glDisable(GL_CONVOLUTION_1D_EXT);
+		glDisable(GL_CONVOLUTION_2D_EXT);
+		glDisable(GL_SEPARABLE_2D_EXT);
+	}
 #endif
 
 #ifdef GL_EXT_histogram
-	glDisable(GL_HISTOGRAM_EXT);
-	glDisable(GL_MINMAX_EXT);
+	if( glext.check("GL_EXT_histogram") ) {
+		glDisable(GL_HISTOGRAM_EXT);
+		glDisable(GL_MINMAX_EXT);
+	}
 #endif
 
 #ifdef GL_EXT_texture3D
-	glDisable(GL_TEXTURE_3D_EXT);
+	if( glext.check("GL_EXT_texture3D") ) {
+		glDisable(GL_TEXTURE_3D_EXT);
+	}
 #endif
 
 	glPushMatrix();

**Comment by mmuman** [comment]
Indeed it's cleaner, thanks.
