### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by VirgilioVasconc** [ideasman42/opentoonz#15]
I have successfully compiled it under Ubuntu 16.04 after adding the GCC 6 PPA and reverting that Mac OS X change (as suggested on https://github.com/ideasman42/opentoonz/issues/13#issuecomment-219911812).

Besides the success on building it, the application doesn't open. After executing the resulting binary, all I get is the splash screen followed by a "segmentation fault" message:

```
$ LD_LIBRARY_PATH=image:toonzlib:toonzfarm/tfarm:tnzbase:tnztools:stdfx:sound:tnzcore:tnzext:colorfx:toonzqt ./OpenToonz_1.0

plugin search directory:/home/USER/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/USER/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
Segmentation fault (core dumped)

```

I have compiled it using the Debug flag:
`cmake -DCMAKE_BUILD_TYPE=Debug`

Any ideas of what should I do?

**Comment by maxolasersquad** [comment]
I'm getting the same thing on two different machines running Ubuntu 16.04 64-bit.

**Comment by andreygursky** [comment]
Please provide additional information. For this you can start OpenToonz under gdb as follows:
```
LD_LIBRARY_PATH=image:toonzlib:toonzfarm/tfarm:tnzbase:tnztools:stdfx:sound:tnzcore:tnzext:colorfx:toonzqt gdb ./OpenToonz_1.0
(gdb) run
```
Let it crash and post here the output of a backtrace and a full one:
```
(gdb) backtrace
(gdb) backtrace full
```

**Comment by VirgilioVasconc** [comment]
Well... I don't know what happened, but now the program has opened. I haven't compiled it again.

The only thing that happened was an apt update of my Ubuntu 16.04 64-bit install...

After I ran your command with gdb everything went apparently ok. In my /var/log/dpkg.log I got an update on my libc-bin package:
`2016-06-02 21:29:03 status installed libc-bin:amd64 2.23-0ubuntu3`

Can @maxolasersquad confirm that, please?

**Comment by maxolasersquad** [comment]
Confirmed. It must have been a broken Ubuntu package causing the problems.
